[project]
name = "titanix-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.15.1",
    "fastapi>=0.115.11",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.39",
    "uvicorn>=0.34.0",
]
